# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - non-dora-delete-me

on:
  push:
    branches:
      - retrieval-eval
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dorakicontainers.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c905edcb4c9147cbb5b49c65c4c16be7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5250aeee80864961bb02a799c0d9aeb2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dorakicontainers.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c905edcb4c9147cbb5b49c65c4c16be7 }}/dorakicontainers/dora-ki-backend-async-single-file:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'non-dora-delete-me'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fee21a6256074db5a6ea56bb96f79b56 }}
        images: 'dorakicontainers.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c905edcb4c9147cbb5b49c65c4c16be7 }}/dorakicontainers/dora-ki-backend-async-single-file:${{ github.sha }}'